### ISSUE TITLE
Update the book

### ISSUE THREAD

**Issue by giggio** [sreejith-ms/Book-of-the-Runtime#1]
Would you update it? If you leave the scripts here I could send a PR.

**Comment by giggio** [comment]
BTW, thanks for making it available in the first place.

**Comment by sreejith-ms** [comment]
@giggio I didn't used any scripts here, I manually combined all of them. Scripts will be a good option to automate this, I will check it.
BTW, this is a surprise for me bcz I never thought anyone will use it.

**Comment by giggio** [comment]
I actually tweeted about it and a lot of people liked it. I guess some people are actually using it.

**Comment by sreejith-ms** [comment]
@giggio Book updated :smiley:
